apiVersion: v1
kind: Service
metadata:
  name: face-recognition-db-service
spec:
  selector:
    app: face-recognition-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: 10.0.1.1