apiVersion: v1
kind: Service
metadata:
  name: face-recognition-service
spec:
  type: LoadBalancer
  selector:
    app: face-recognition
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000